# Generated by Django 5.1.4 on 2025-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mon_projet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
